3D Scene consuming 100% CPU resources issue fix (2)
MetaCell/geppetto-meta pull request #152
Opened 2021-09-01 15:27 UTC by enicolasgomez

had to create a new PR than #150 as started fresh from a new branch, here's the change log:

1. The animation frame on ThreeDEngine is not a recursive loop anymore, this is the starting point to solve this issue
2. TrackballControls has been kept in favor of OrbitControls
3. ThreeDEngine instances is now exposed to TrackballControl component
4. Internally, Trackballcontrol uses ThreeDEngine.requestAnimaionFrame() internally on `update()` only when the lastposition of the camera has changed
5. `defaultCameraControlsHandler` on Canvas will end up requesting an animation frame. This is needed as there's no a constant loop anymore
6. handlers have been added to Canvas React component to requestAnimationFrame() upon doucment loading

#150 
https://github.com/MetaCell/open-physiology-viewer/issues/31

2021-09-01 17:13 UTC, enicolasgomez commented
One thing that worth mentioning as an improvement is subscribing to TrackballControls events from ThreeDEngine and fire the update event from there, internally to keep trackballcontrols agnostic from the engine.

2021-09-02 08:56 UTC, afonsobspinto requested changes
Seems like the previous issues were fixed, thanks for that :+1: 

However, and I'm not sure if this was already happening in the previous PR, now I noticed that the selection action is one frame behind / delayed (perhaps not triggering the requestFrame method?). Check below:

![demo](https://user-images.githubusercontent.com/19196034/131812993-6302dafd-32b0-4119-b268-22a20b3ee3a2.gif)

Only after changing the camera, the selected object changes color.

Besides that, I agree with your suggestion of using events to loose the coupling between the engine and the trackball controls. I would see this change as a nice to have and not something mandatory to approve.

2021-09-02 13:01 UTC, enicolasgomez commented
- Using events to loose the coupling between the engine and the trackball
- Plugged in intersect event to rendering 
- Incremented autorotate timeout to increment FPS

2021-09-03 09:01 UTC, afonsobspinto commented on geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/ThreeDEngine.js
> +      this
No longer needed

2021-09-03 09:03 UTC, merged